### PR TITLE
Allow wider python range (3.9-3.12)

### PR DESCRIPTION
**Pull request by asiomchen**
Hi, thank you for the very useful tool. I noticed, that python range is quite narrow, limiting use of the modern language features and integration with other tools. This PR aims to solve it. If you have any questions or suggestions, let me know

## Dependency Updates:

* [`.pre-commit-config.yaml`](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L17-R17): Updated `black` version from `22.0.0` to `24.1.0`. (22.0.0 is no longer on git)
* [`env-dev.yml`](diffhunk://#diff-6adf75c0ddd765f4a0a9fabaaaa7c8f8c908a282e8d4ae2ae5e8c09aa3368e17L6-R7): Updated `python` version range to `<3.13` and `poetry` version to `>=1.2.0`. (this poetry range is better, because from it `[tool.poetry.group.dev.dependencies]` is a default way to specify dev dependencies)
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L3-R3): Updated project version to `1.8.0`, `python` version range to `<3.13`, `pandas` to `^2.0.0`, and added `dask>=2024.4.1` dependency

## Migration to Pandas 2.0 

Migration is needed due to dask/dask#11038 

* [`rxnutils/pipeline/actions/dataframe_mod.py`](diffhunk://#diff-bbeaa0e9c99e224a6f6eb6548aa1414641b0b1ddf17c48d15c5c9676c682307cL33-R33): Replaced positional argument `1` with keyword argument `axis=1` in `data.drop` method calls
* Used column names as strings in `isotop_info` and updated `str.replace` to use `regex=True`.

## Testing Enhancements:

* [`tests/test_reaction.py`](diffhunk://#diff-ad689539c89b473aa1decd282b1781a172a505c256c262620cba6248100502ebL2-R2): Added `monkeypatch` to `test_timedout_template_creation` to set a lower timeout for `_generate_rdchiral_template`

### CODE REVIEW

**Comment by SGenheden** [comment]
Thanks @asiomchen for this! Much appreciated. We will review this over the next couple of days.

**Comment by asiomchen** [comment]
Cool, @SGenheden I was also thinking about adding linting and formation powered by [ruff](https://docs.astral.sh/ruff/). 
I saw, that you have linter in the TODOs, would you be interested in accepting such changes?

**Comment by SGenheden** [comment]
We use pylint currently, having looked into other options - but for now nothing is decided. The change to another linter would carry over to other codebases as well, so it is not something that we consider for only rxnutils.

**Comment by asiomchen** [comment]
Hey @SGenheden , I assume this PR could now be closed, as the changes are merged in the other PR?

P.S I don't insist, but it might be nice to add me to the contributors list some time😊

**Comment by SGenheden** [comment]
Yes. Most of it is included in the new release. The only thing I opted not to include was the monkeypatched test. The reason we did it like this was that some of the changes was already introduced in our internal version, and we want to allow for both pandas 1 and 2
I will add you to the contributors list tomorrow, that was on my to-do. Thanks for the help.

**Pull request closed without merging**
